/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:0ea46efa-e871-43f4-83fa-4d5b614993a9",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_bwyAAvj6H",
    "aws_user_pools_web_client_id": "3v5edopki0sss9u62qqqntjhai",
    "oauth": {}
};


export default awsmobile;
